# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Continuous integration

# Run the CI on any direct push to a branch on this repository or on pull request
# branches
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Update submodules
      run: |
        git submodule update --init --recursive --depth=1
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=src" >> $GITHUB_ENV
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        invoke lint
    - name: Check black formatting of code, tests and development scripts
      run: |
        invoke check-code-format
    - name: Test with pytest
      run: |
        invoke test --external

